Разбил модели на отдельные файлы в новой папке Чтобы избавиться от циклического импорта ImportError: cannot import name 'User' from partially initialized module 'users.models' (most likely due to a circular import)